import hashlib
import json
import os
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Dict, List, Any, Optional, TypedDict, Annotated
import operator
from dataclasses import dataclass, field

from langgraph.graph import StateGraph, END
import chromadb
from chromadb.config import Settings

from openrouter_client import OpenRouterClient, MODEL_V3
from schemas import Resume

# Fixed scoring weights — never generated by LLM to avoid per-run variance
SCORE_WEIGHTS = {"skills": 0.40, "experience": 0.35, "education": 0.15, "projects": 0.10}

# Retrieval is deliberately broader than the LLM stage.  The limits are
# configurable so recall can be evaluated and tuned without changing code.
RETRIEVAL_TOP_K = int(os.getenv("RETRIEVAL_TOP_K", "75"))
CROSS_ENCODER_TOP_K = int(os.getenv("CROSS_ENCODER_TOP_K", "25"))
LLM_TOP_K = int(os.getenv("LLM_TOP_K", "15"))

# Weighted Reciprocal Rank Fusion — combines three ranking signals.
# 2 of 3 signals (cross-encoder, vector) are fully deterministic, which damps
# LLM score jitter; rank-based fusion needs no cross-scale normalisation.
#
# Env-overridable like the funnel limits above, so the cross-encoder : vector
# ratio can be swept without editing code.
#
# These weights are NOT currently justified by evidence. They were set CE-light to
# protect real-CV ranking against a regression that has since been withdrawn — the
# pool behind it turned out to be unrankable (no candidate suited the JD, so the
# labels carried no true order). On the one slice that still measures, synthetic
# seeds, quality rises monotonically with cross-encoder share, which argues the
# opposite way. That slice cannot settle it either: 0/45 seeds exceed the
# cross-encoder's 512-token limit while 7/11 real CVs do, so it is structurally
# blind to truncation. Treat this ratio as unresolved pending a labelled real-CV
# pool; do not "fix" it against seeds alone (see OPTIMIZATION_LOOP.md).
RRF_K = int(os.getenv("RRF_K", "60"))
FUSION_WEIGHTS = {
    "llm":           float(os.getenv("FUSION_W_LLM", "0.50")),
    "cross_encoder": float(os.getenv("FUSION_W_CE",  "0.30")),
    "vector":        float(os.getenv("FUSION_W_VEC", "0.20")),
}


def rrf_fuse(entries: List[Dict[str, Any]], k: int = RRF_K,
             weights: Dict[str, float] = FUSION_WEIGHTS) -> List[Dict[str, Any]]:
    """
    Weighted RRF over three signals: match_score (LLM), ce_score (cross-encoder),
    vector_similarity (bi-encoder cosine).  Entries missing a signal are ranked
    worst in that signal's list.  Sorts in place-order, assigns rank + fused_score.
    """
    if not entries:
        return entries

    def _rank_map(key: str) -> Dict[str, int]:
        present = [e for e in entries if e.get(key) is not None]
        absent  = [e for e in entries if e.get(key) is None]
        ordered = sorted(
            present,
            key=lambda e: (-float(e.get(key) or 0), str(e.get("candidate_id", ""))),
        )
        ranks = {str(e.get("candidate_id", "")): i + 1 for i, e in enumerate(ordered)}
        worst = len(ordered) + 1
        for e in absent:
            ranks[str(e.get("candidate_id", ""))] = worst
        return ranks

    llm_ranks = _rank_map("match_score")
    ce_ranks  = _rank_map("ce_score")
    vec_ranks = _rank_map("vector_similarity")

    for e in entries:
        cid = str(e.get("candidate_id", ""))
        fused = (
            weights["llm"]           / (k + llm_ranks[cid]) +
            weights["cross_encoder"] / (k + ce_ranks[cid])  +
            weights["vector"]        / (k + vec_ranks[cid])
        )
        e["fused_score"] = round(fused * 1000, 2)

    fused_sorted = sorted(
        entries,
        key=lambda e: (-e["fused_score"], str(e.get("candidate_id", ""))),
    )
    for i, e in enumerate(fused_sorted):
        e["rank"] = i + 1
    return fused_sorted


# ─── LangGraph State ──────────────────────────────────────────────────────────

class PipelineState(TypedDict):
    job_description: str
    required_skills: List[str]
    min_experience_years: Optional[int]
    required_education: Optional[str]
    evaluation_criteria: Optional[Dict[str, Any]]
    plan: Optional[Dict[str, Any]]
    search_queries: List[str]
    retrieved_ids: List[str]                 # LLM shortlist only
    retrieval_ranked_ids: List[str]          # complete returned ranking set
    retrieved_resumes: Dict[str, Dict[str, Any]]
    candidate_names: Dict[str, str]
    retrieved_similarities: Dict[str, float]   # cid → max cosine sim across queries
    ce_scores: Dict[str, float]                # cid → sigmoid(cross-encoder logit)
    evaluations: Annotated[List[Dict[str, Any]], operator.add]
    critique: Optional[Dict[str, Any]]
    final_rankings: List[Dict[str, Any]]
    interview_questions: Dict[str, Any]   # {candidate_id: {categories...}}
    screening_stats: Dict[str, int]
    errors: Annotated[List[str], operator.add]


@dataclass
class ScreeningQuery:
    job_description: str
    required_skills: List[str] = field(default_factory=list)
    min_experience_years: Optional[int] = None
    required_education: Optional[str] = None
    evaluation_criteria: Optional[Dict[str, Any]] = None


# ─── ChromaDB Vector Store ────────────────────────────────────────────────────

class CandidateVectorStore:
    """ChromaDB-backed vector store for candidate embeddings and semantic search"""

    def __init__(self, persist_path: str = "./chroma_db"):
        self.client = chromadb.PersistentClient(path=persist_path)
        # Uses chromadb's default all-MiniLM-L6-v2 embedding function
        self.collection = self.client.get_or_create_collection(
            name="candidates",
            metadata={"hnsw:space": "cosine"}
        )

    def add_candidate(self, resume: Resume, candidate_id: str):
        """Embed and store candidate resume"""
        text = self._resume_to_text(resume)
        name = resume.contact_info.name if resume.contact_info else "Unknown"

        # Upsert so re-adding same ID doesn't error
        self.collection.upsert(
            ids=[candidate_id],
            documents=[text],
            metadatas=[{
                "name": name,
                "email": resume.contact_info.email or "" if resume.contact_info else "",
                "skills_flat": self._skills_flat(resume),
                "resume_json": json.dumps(resume.dict()),
            }]
        )

    def search(self, query: str, top_k: int = 10) -> List[Dict[str, Any]]:
        """Semantic search returning top_k candidates"""
        return self.search_many([query], top_k)[0]

    def search_many(self, queries: List[str], top_k: int = 10) -> List[List[Dict[str, Any]]]:
        """Same as search(), for several queries in ONE ChromaDB round trip.

        Embedding the queries is a fixed cost paid per call, not per query, so
        issuing them together is markedly cheaper than looping — measured 800ms
        to ~378ms for the three planner queries. Returns one result list per
        query, in the order given.
        """
        if not queries:
            return []
        results = self.collection.query(
            query_texts=list(queries),
            n_results=min(top_k, self.collection.count() or 1)
        )

        out: List[List[Dict[str, Any]]] = []
        ids_per_query = (results or {}).get("ids") or []
        for qi in range(len(queries)):
            candidates: List[Dict[str, Any]] = []
            if qi < len(ids_per_query) and ids_per_query[qi]:
                dists = (results.get("distances") or [None] * len(queries))[qi]
                metas = (results.get("metadatas") or [None] * len(queries))[qi]
                for i, cid in enumerate(ids_per_query[qi]):
                    distance = dists[i] if dists else 1.0
                    candidates.append({
                        "id": cid,
                        # cosine: distance=0 → similarity=1
                        "similarity_score": round(1 - distance, 4),
                        "metadata": metas[i] if metas else {}
                    })
            out.append(candidates)
        return out

    def count(self) -> int:
        return self.collection.count()

    def get_candidate_data(self, candidate_id: str) -> Optional[dict]:
        """Retrieve resume dict from ChromaDB (stored as JSON in metadata)."""
        try:
            result = self.collection.get(ids=[candidate_id], include=["metadatas"])
            if result and result.get("ids"):
                rj = result["metadatas"][0].get("resume_json", "")
                return json.loads(rj) if rj else None
        except Exception:
            pass
        return None

    def get_candidate_data_many(self, candidate_ids: List[str]) -> Dict[str, dict]:
        """Fetch resume JSON for many candidates in one ChromaDB round trip."""
        if not candidate_ids:
            return {}
        try:
            result = self.collection.get(ids=candidate_ids, include=["metadatas"])
            output: Dict[str, dict] = {}
            for cid, metadata in zip(result.get("ids", []), result.get("metadatas", []) or []):
                raw = (metadata or {}).get("resume_json", "")
                if raw:
                    output[cid] = json.loads(raw)
            return output
        except Exception:
            return {}

    def pool_manifest(self) -> Dict[str, str]:
        """Stable content fingerprint per candidate, used to validate cached jobs."""
        result = self.collection.get(include=["documents"])
        return {
            cid: hashlib.sha256((document or "").encode("utf-8")).hexdigest()[:16]
            for cid, document in zip(result.get("ids", []), result.get("documents", []) or [])
        }

    def pool_fingerprint(self) -> str:
        manifest = self.pool_manifest()
        serialised = "\n".join(f"{cid}:{manifest[cid]}" for cid in sorted(manifest))
        return hashlib.sha256(serialised.encode("utf-8")).hexdigest()[:16]

    def _resume_to_text(self, resume: Resume) -> str:
        parts = []
        if resume.professional_summary:
            parts.append(resume.professional_summary)
        for s in resume.skills:
            parts.extend(s.skills)
        for exp in resume.experience:
            if exp.position:
                parts.append(exp.position)
            if exp.description:
                parts.append(exp.description)
            if exp.technologies:
                parts.extend(exp.technologies)
            if exp.achievements:
                parts.extend(exp.achievements)
        for edu in resume.education:
            if edu.degree:
                parts.append(edu.degree)
            if edu.field_of_study:
                parts.append(edu.field_of_study)
        for cert in resume.certifications:
            if cert.title:
                parts.append(cert.title)
        for proj in resume.projects:
            if proj.description:
                parts.append(proj.description)
            if proj.technologies:
                parts.extend(proj.technologies)
        return " ".join(filter(None, parts))

    def _skills_flat(self, resume: Resume) -> str:
        return ", ".join(skill for s in resume.skills for skill in s.skills)


# ─── Agent Nodes ──────────────────────────────────────────────────────────────

def _parse_json_response(response: str) -> dict:
    """Robustly extract JSON from an LLM response (handles fences, prose, trailing text)."""
    from openrouter_client import _extract_json
    return _extract_json(response)


def _score_component(value: Any, label: str) -> float:
    """Validate a model-supplied component score before it affects ranking."""
    try:
        score = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Invalid {label}_score: {value!r}") from exc
    if not 0 <= score <= 100:
        raise ValueError(f"{label}_score outside 0-100: {score}")
    return score


def evaluate_resume_against_jd(
    llm: OpenRouterClient,
    job_description: str,
    candidate_id: str,
    resume_dict: dict,
    plan: Optional[Dict[str, Any]] = None,
) -> dict:
    """Canonical evaluator shared by full and cached-delta screening paths."""
    plan = plan or {}
    name = ((resume_dict.get("contact_info") or {}).get("name")) or candidate_id
    prompt = f"""You are an expert recruiter. Evaluate this candidate against the job description.

Job Description:
{job_description}

Scoring weights (for reference): skills={SCORE_WEIGHTS['skills']}, experience={SCORE_WEIGHTS['experience']}, education={SCORE_WEIGHTS['education']}, projects={SCORE_WEIGHTS['projects']}
Hard requirements: {json.dumps(plan.get('hard_requirements', []))}
Nice to have: {json.dumps(plan.get('nice_to_have', []))}

Candidate Resume (JSON):
{json.dumps(resume_dict, indent=2)}

Return ONLY valid JSON:
{{
  "skills_score": <float 0-100>,
  "experience_score": <float 0-100>,
  "education_score": <float 0-100>,
  "projects_score": <float 0-100>,
  "strengths": ["<strength1>", "<strength2>"],
  "weaknesses": ["<gap1>", "<gap2>"],
  "matched_skills": ["<skill1>"],
  "missing_skills": ["<skill1>"],
  "meets_hard_requirements": <true|false>,
  "overall_recommendation": "<STRONG_MATCH|MATCH|WEAK_MATCH|NOT_QUALIFIED>",
  "reasoning": "<1-2 sentence summary>",
  "suggested_interview_questions": ["<q1>", "<q2>"]
}}"""
    response = llm.call_llm(
        [{"role": "user", "content": prompt}],
        model=MODEL_V3,
        temperature=0.1,
        json_mode=True,
    )
    evaluation = _parse_json_response(response)
    components = {
        "skills": _score_component(evaluation.get("skills_score"), "skills"),
        "experience": _score_component(evaluation.get("experience_score"), "experience"),
        "education": _score_component(evaluation.get("education_score"), "education"),
        "projects": _score_component(evaluation.get("projects_score"), "projects"),
    }
    evaluation["match_score"] = round(sum(components[key] * SCORE_WEIGHTS[key] for key in components), 1)
    evaluation["candidate_id"] = candidate_id
    evaluation["candidate_name"] = name
    evaluation["screening_status"] = "llm_scored"
    return evaluation


class AgentNodes:
    def __init__(self, llm: OpenRouterClient, store: CandidateVectorStore, candidate_store: Dict[str, Resume]):
        self.llm = llm
        self.store = store
        self.candidates = candidate_store

    # ── Planner ───────────────────────────────────────────────────────────────
    def planner_node(self, state: PipelineState) -> dict:
        """Decompose the job description into a structured screening plan"""
        from database import make_jd_hash, get_plan_for_hash, save_plan_for_hash, is_connected

        jd_hash = make_jd_hash(state['job_description'])

        # Return cached plan if available — same JD always produces same queries/requirements
        if is_connected():
            cached = get_plan_for_hash(jd_hash)
            if cached:
                return {
                    "plan": cached,
                    "search_queries": cached.get("search_queries", [state['job_description']])
                }

        prompt = f"""You are a recruiting planner. Given the job description below, create a structured screening plan.

Job Description:
{state['job_description']}

Required Skills: {', '.join(state.get('required_skills', []) or [])}
Min Experience: {state.get('min_experience_years')} years
Required Education: {state.get('required_education', 'Not specified')}

Return ONLY valid JSON:
{{
  "search_queries": ["<semantic query 1>", "<semantic query 2>", "<semantic query 3>"],
  "evaluation_focus_areas": ["<area1>", "<area2>"],
  "hard_requirements": ["<must-have 1>", "<must-have 2>"],
  "nice_to_have": ["<optional 1>"]
}}"""

        try:
            resp = self.llm.call_llm(
                [{"role": "user", "content": prompt}], model=MODEL_V3, temperature=0.1, json_mode=True
            )
            plan = _parse_json_response(resp)
            if is_connected():
                save_plan_for_hash(jd_hash, plan)
            return {
                "plan": plan,
                "search_queries": plan.get("search_queries", [state['job_description']])
            }
        except Exception as e:
            return {"plan": {}, "search_queries": [state['job_description']], "errors": [f"Planner error: {e}"]}

    # ── Retriever ─────────────────────────────────────────────────────────────
    def retriever_node(self, state: PipelineState) -> dict:
        """Use a broad deterministic shortlist before reranking and LLM work."""
        pool_size = self.store.count()
        if pool_size == 0:
            return {"retrieved_ids": [], "errors": ["No candidates indexed in ChromaDB"]}

        # Fetch every candidate for each query (top_k = full pool), then dedup.
        # This guarantees newly uploaded resumes are always evaluated regardless
        # of how they rank against existing candidates.
        # Keep the MAX similarity seen across queries per candidate — this is the
        # vector signal fed into RRF fusion downstream.
        # One round trip for every planner query — the embedding cost is per
        # call, not per query, so looping here was the bulk of retrieval latency.
        best_sim: Dict[str, float] = {}
        for hits in self.store.search_many(
            state.get("search_queries", []), top_k=min(RETRIEVAL_TOP_K, pool_size)
        ):
            for hit in hits:
                cid = hit["id"]
                best_sim[cid] = max(best_sim.get(cid, 0.0), hit["similarity_score"])

        retrieval_ids = sorted(best_sim, key=lambda c: (-best_sim[c], c))[:RETRIEVAL_TOP_K]
        if not retrieval_ids:
            return {"retrieved_ids": [], "errors": ["Retriever returned no candidates"]}

        # Cross-encoder reranking signal — score (JD, embedded document) pairs.
        # Uses the exact text ChromaDB embedded, so no re-serialisation drift.
        data = self.store.collection.get(ids=retrieval_ids, include=["documents", "metadatas"])
        documents = dict(zip(data.get("ids", []), data.get("documents", []) or []))
        metadata = dict(zip(data.get("ids", []), data.get("metadatas", []) or []))
        resumes: Dict[str, dict] = {}
        names: Dict[str, str] = {}
        for cid in retrieval_ids:
            meta = metadata.get(cid) or {}
            try:
                raw = meta.get("resume_json", "")
                if raw:
                    resumes[cid] = json.loads(raw)
            except json.JSONDecodeError:
                continue
            names[cid] = meta.get("name") or ((resumes.get(cid, {}).get("contact_info") or {}).get("name")) or cid
        ce_candidates = retrieval_ids[:min(CROSS_ENCODER_TOP_K, len(retrieval_ids))]
        ce_map: Dict[str, float] = {}
        try:
            import reranker
            scores = reranker.ce_scores(
                state.get("job_description", ""), [documents.get(cid, "") for cid in ce_candidates]
            )
            ce_map = {cid: round(score, 4) for cid, score in zip(ce_candidates, scores)}
        except Exception:
            pass  # fusion degrades gracefully — missing signal ranks worst

        return {
            "retrieved_ids": sorted(
                ce_candidates,
                key=lambda cid: (-ce_map.get(cid, float("-inf")), -best_sim[cid], cid),
            )[:min(LLM_TOP_K, len(ce_candidates))],
            "retrieval_ranked_ids": retrieval_ids,
            "retrieved_resumes": resumes,
            "candidate_names": names,
            "retrieved_similarities": best_sim,
            "ce_scores": ce_map,
            "screening_stats": {
                "pool_size": pool_size,
                "retrieved_count": len(retrieval_ids),
                "cross_encoder_count": len(ce_candidates),
                "llm_evaluated_count": min(LLM_TOP_K, len(ce_candidates)),
            },
        }

    # ── Evaluator ─────────────────────────────────────────────────────────────
    def evaluator_node(self, state: PipelineState) -> dict:
        """Score each retrieved candidate against the JD — parallel LLM calls."""
        plan = state.get("plan", {})
        retrieved_ids = state.get("retrieved_ids", [])

        def eval_one(cid: str) -> dict:
            if cid in self.candidates:
                resume_dict = self.candidates[cid].dict()
            else:
                resume_dict = state.get("retrieved_resumes", {}).get(cid)
                if not resume_dict:
                    return None

            try:
                return evaluate_resume_against_jd(
                    self.llm, state["job_description"], cid, resume_dict, plan
                )
            except Exception as e:
                return {"candidate_id": cid, "candidate_name": state.get("candidate_names", {}).get(cid, cid),
                        "match_score": 0, "overall_recommendation": "ERROR", "reasoning": str(e)}

        evaluations = []
        with ThreadPoolExecutor(max_workers=6) as pool:
            futures = {pool.submit(eval_one, cid): cid for cid in retrieved_ids}
            for future in as_completed(futures):
                result = future.result()
                if result:
                    evaluations.append(result)

        # Sort by candidate_id for deterministic ordering passed to critique
        evaluations.sort(key=lambda x: x.get("candidate_id", ""))
        return {"evaluations": evaluations}

    # ── Critique ──────────────────────────────────────────────────────────────
    def critique_node(self, state: PipelineState) -> dict:
        """Validate evaluations for consistency and flag any issues"""
        evaluations = state.get("evaluations", [])
        if not evaluations:
            return {"critique": {"is_valid": False, "issues": ["No candidates evaluated"]}}

        prompt = f"""You are a QA reviewer for a recruitment pipeline. Review these candidate evaluations for consistency.

Job Description (summary):
{state['job_description'][:500]}

Evaluations:
{json.dumps(evaluations, indent=2)}

Check for: ignored hard requirements, inconsistent recommendations relative to scores.

Return ONLY valid JSON:
{{
  "is_valid": <true|false>,
  "issues_found": ["<issue1>"],
  "recommended_for_interview": ["<candidate_id1>", "<candidate_id2>"],
  "overall_quality": "<GOOD|ACCEPTABLE|NEEDS_REVIEW>",
  "summary": "<1-2 sentence summary of the candidate pool>"
}}"""

        try:
            resp = self.llm.call_llm(
                [{"role": "user", "content": prompt}], model=MODEL_V3, temperature=0.1, json_mode=True
            )
            critique = _parse_json_response(resp)
            return {"critique": critique}
        except Exception as e:
            return {"critique": {"is_valid": False, "issues_found": [f"Critique error: {e}"]}, "errors": [str(e)]}

    # ── Synthesizer ───────────────────────────────────────────────────────────
    def synthesizer_node(self, state: PipelineState) -> dict:
        """Produce final ranked list — weighted RRF over LLM + cross-encoder + vector signals."""
        evaluations = state.get("evaluations", [])
        critique = state.get("critique", {})
        recommended_ids = set(critique.get("recommended_for_interview", []))
        sims = state.get("retrieved_similarities", {}) or {}
        ces  = state.get("ce_scores", {}) or {}

        scored_ids = {ev.get("candidate_id") for ev in evaluations}
        ranking_entries = list(evaluations)
        for cid in state.get("retrieval_ranked_ids", []):
            if cid not in scored_ids:
                ranking_entries.append({
                    "candidate_id": cid,
                    "candidate_name": state.get("candidate_names", {}).get(cid, cid),
                    "match_score": None,
                    "overall_recommendation": "NOT_EVALUATED",
                    "screening_status": "retrieval_only",
                    "strengths": [], "weaknesses": [],
                    "matched_skills": [], "missing_skills": [],
                })

        for ev in ranking_entries:
            cid = ev.get("candidate_id", "")
            ev["vector_similarity"] = sims.get(cid)
            ev["ce_score"]          = ces.get(cid)

        ranked = rrf_fuse(ranking_entries)
        for ev in ranked:
            ev["recommended_for_interview"] = ev.get("candidate_id") in recommended_ids

        return {"final_rankings": ranked}

    # ── Interview Question Generator ──────────────────────────────────────────
    def interview_questions_node(self, state: PipelineState) -> dict:
        """Generate tailored interview questions for recommended candidates — parallel."""
        # Interview questions are generated only when a recruiter starts one.
        return {"interview_questions": {}}

        recommended = [r for r in state.get("final_rankings", []) if r.get("recommended_for_interview")]

        def gen_questions(ranking: dict) -> tuple:
            cid = ranking["candidate_id"]
            if cid in self.candidates:
                resume_dict = self.candidates[cid].dict()
            else:
                resume_dict = self.store.get_candidate_data(cid)
                if not resume_dict:
                    return cid, {"error": "Resume data not found"}

            prompt = f"""You are a senior technical interviewer. Generate a tailored interview question set for this candidate.

Role being hired for:
{state['job_description']}

Candidate resume:
{json.dumps(resume_dict, indent=2)}

Screening evaluation:
- Match score: {ranking.get('match_score')}/100
- Strengths: {json.dumps(ranking.get('strengths', []))}
- Weaknesses / gaps: {json.dumps(ranking.get('weaknesses', []))}
- Missing skills: {json.dumps(ranking.get('missing_skills', []))}
- Matched skills: {json.dumps(ranking.get('matched_skills', []))}

Generate questions that:
1. Probe depth on claimed strengths (not surface-level)
2. Directly challenge each identified gap or missing skill
3. Dig into specific projects they listed (not generic)
4. Include at least one system design / architecture question relevant to the role
5. Include one behavioral question tied to a real gap (e.g. "Tell me about leading a team" if leadership is missing)

Return ONLY valid JSON:
{{
  "candidate_name": "<name>",
  "technical_depth": [
    {{"question": "<q>", "what_to_look_for": "<expected signal>", "follow_up": "<follow up if answer is shallow>"}}
  ],
  "gap_probing": [
    {{"gap": "<missing skill or weakness>", "question": "<q>", "what_to_look_for": "<signal>"}}
  ],
  "project_specific": [
    {{"project": "<project name from resume>", "question": "<q>", "what_to_look_for": "<signal>"}}
  ],
  "system_design": [
    {{"question": "<q>", "what_to_look_for": "<signal>"}}
  ],
  "behavioral": [
    {{"question": "<q>", "what_to_look_for": "<signal>"}}
  ]
}}"""

            try:
                resp = self.llm.call_llm([{"role": "user", "content": prompt}], model=MODEL_V3, temperature=0.1)
                questions = _parse_json_response(resp)
                questions["candidate_id"] = cid
                questions["rank"] = ranking["rank"]
                questions["match_score"] = ranking.get("match_score")
                return cid, questions
            except Exception as e:
                return cid, {"error": str(e)}

        # Cap at top 5 recommended to keep IQ generation fast
        recommended = recommended[:5]

        results: Dict[str, Any] = {}
        with ThreadPoolExecutor(max_workers=5) as pool:
            futures = [pool.submit(gen_questions, r) for r in recommended]
            for future in as_completed(futures):
                cid, questions = future.result()
                results[cid] = questions

        return {"interview_questions": results}


# ─── Graph Builder ────────────────────────────────────────────────────────────

def _timed_node(name: str, fn, sink: Dict[str, float]):
    """Wrap a graph node so its wall-clock lands in `sink` without touching its logic.

    Speed and ranking quality have to be readable from the same run — optimising
    one blind to the other is how a pipeline gets fast and wrong.
    """
    def wrapper(state):
        t0 = time.perf_counter()
        try:
            return fn(state)
        finally:
            sink[name] = round(time.perf_counter() - t0, 3)
    return wrapper


def build_screening_graph(llm: OpenRouterClient, store: CandidateVectorStore,
                          candidate_store: Dict[str, Resume],
                          timings: Optional[Dict[str, float]] = None):
    """Construct and compile the LangGraph screening pipeline"""
    nodes = AgentNodes(llm, store, candidate_store)
    sink = timings if timings is not None else {}

    graph = StateGraph(PipelineState)
    graph.add_node("planner", _timed_node("planner", nodes.planner_node, sink))
    graph.add_node("retriever", _timed_node("retriever", nodes.retriever_node, sink))
    graph.add_node("evaluator", _timed_node("evaluator", nodes.evaluator_node, sink))
    graph.add_node("critique", _timed_node("critique", nodes.critique_node, sink))
    graph.add_node("synthesizer", _timed_node("synthesizer", nodes.synthesizer_node, sink))
    graph.add_node("interview_questions",
                   _timed_node("interview_questions", nodes.interview_questions_node, sink))

    graph.set_entry_point("planner")
    graph.add_edge("planner", "retriever")
    graph.add_edge("retriever", "evaluator")
    graph.add_edge("evaluator", "critique")
    graph.add_edge("critique", "synthesizer")
    graph.add_edge("synthesizer", "interview_questions")
    graph.add_edge("interview_questions", END)

    return graph.compile()


# ─── Pipeline Facade ──────────────────────────────────────────────────────────

class ScreeningPipeline:
    def __init__(self, openrouter_api_key: Optional[str] = None, chroma_path: str = "./chroma_db"):
        self.llm = OpenRouterClient(openrouter_api_key)
        self.store = CandidateVectorStore(chroma_path)
        self.candidate_store: Dict[str, Resume] = {}
        self._graph = None
        self.node_timings: Dict[str, float] = {}

    def _get_graph(self):
        if self._graph is None:
            self._graph = build_screening_graph(
                self.llm, self.store, self.candidate_store, self.node_timings
            )
        return self._graph

    def add_candidate(self, resume: Resume, candidate_id: str):
        self.candidate_store[candidate_id] = resume
        self.store.add_candidate(resume, candidate_id)
        self._graph = None  # Rebuild graph with updated store

    def screen_candidates(self, query: ScreeningQuery) -> dict:
        """Run the full LangGraph pipeline and return state"""
        graph = self._get_graph()

        initial_state: PipelineState = {
            "job_description": query.job_description,
            "required_skills": query.required_skills or [],
            "min_experience_years": query.min_experience_years,
            "required_education": query.required_education,
            "evaluation_criteria": query.evaluation_criteria,
            "plan": None,
            "search_queries": [],
            "retrieved_ids": [],
            "retrieval_ranked_ids": [],
            "retrieved_resumes": {},
            "candidate_names": {},
            "evaluations": [],
            "critique": None,
            "final_rankings": [],
            "interview_questions": {},
            "screening_stats": {},
            "errors": []
        }

        self.node_timings.clear()
        t0 = time.perf_counter()
        state = graph.invoke(initial_state)
        state["node_timings"] = dict(self.node_timings)
        state["node_timings"]["_total"] = round(time.perf_counter() - t0, 3)
        return state
